### ISSUE TITLE
Indicate what version of NodeCG a bundle is compatible with

### ISSUE THREAD

**Issue by Lange** [nodecg/awesome-nodecg#1]
I'm not sure yet what the best way of going about this is. My first thought is to have separate `*.md` files for each version of NodeCG. `README.md` would always point to the newest version of NodeCG, and near the top somewhere we'd have a little blurb with a link to the documents for older versions. Thoughts?

**Comment by ProbablePrime** [comment]
This would allow an easier way for newcomers to nodecg to workout which bundles were supported in which versions and as authors update their bundles they can be included in other lists. 

Its a lot better than what I had planned which was suffixing each item with the version that would of become messy quickely.

:+1:

**Comment by coolacid** [comment]
Would it make some sense to use something along the lines of :: https://help.github.com/articles/using-jekyll-with-pages/ 

One could then tag the bundles and have the generator "build" the details. Direct people to the github page for easier finding of bundles?

**Comment by Lange** [comment]
@coolacid I'm personally not too keen on turning this into a gh-pages repo and adding a build process. Keeping everything in a handful of markdown files keeps the barrier to contribution low.

**Comment by ProbablePrime** [comment]
@coolacid I agree with Lange on this. these lists are meant to be quick jump lists to cool stuff and aren't really designed to be webpages.

**Comment by Lange** [comment]
Closed by 47812161391b0f6fb15b9ece7b4ba6036f186d91
