### ISSUE TITLE
Add to Awesome list

### ISSUE THREAD

**Issue by Lange** [nodecg/awesome-nodecg#8]
Open a PR over at [sindresorhus/awesome](https://github.com/sindresorhus/awesome) to add awesome-nodecg to the list.

@ProbablePrime, I'll let you have the honors. :grin:

**Comment by ProbablePrime** [comment]
@Lange Which section do you think this belongs in over on the awesome list?

**Comment by Lange** [comment]
To me it looks like it belongs in the Misc category.

**Comment by Lange** [comment]
>I'm unfortunately going to pass on this for now. The list is a good start, but the library itself isn't well known enough and the list is very light on content.
